### ISSUE TITLE
We need to add camera offset! 

### ISSUE THREAD

**Issue by Code-MonkeyZhang** [PennState-RoboX/Robomaster2022-CV#13]
Although we can do some sort of auto-aim right now, it’s the camera pointing at the target, not the barrel, we need to test and add an offset.

**Comment by idhantgulati** [comment]
added offset

**Comment by idhantgulati** [comment]
need to fix the camera resolution to the max (ie 1080×1440). whenever CV is restarted it defaults back to 1280×720 and has to be manually set to max resolution.
