### ISSUE TITLE
Comment ArmorDetect File

### ISSUE THREAD

**Issue by Pranav-Karra-3301** [PennState-RoboX/Robomaster2022-CV#5]
We need comments on the main files so that they are easier to understand. 

People who have worked on the other files can comment the respective parts in the ArmorDetect File

@MarmikChaudhari - kinematic_prediction.py
@Pranav-Karra-3301 - UART_UTIL.py
@Idhant297 - Target.py and Sort.py

**Comment by Code-MonkeyZhang** [comment]
This is a good practice, but directly committing your comments one by one will add redundancy to our commit history. 

So I opened a new main branch and kept your comments in another branch "add-comment". You can feel free to add comments in that branch. Once you're done, you can create a new PR to the main, then we could merge your commented branch. By doing so, all your comments will combine as only one merge commit in the main's commit history.
